"""
CEFR Rubrics and linguistic evaluation standards for language proficiency classification.
Supports German (de), English (en), and Norwegian (no/nb/nn).
"""

def get_cefr_rubric(target_language: str = "de") -> str:
    """Returns a tailored, highly accurate dual CEFR rubric (Grammar + Vocabulary) for the target language (de, en, no)."""
    code = (target_language or "de").lower().strip()

    if code == "en":
        return (
            "КРИТЕРИИ CEFR ДЛЯ АНГЛИЙСКОГО ЯЗЫКА (определяй уровень как МАКСИМУМ из сложности грамматики и сложности лексики):\n\n"
            "1. ГРАММАТИКА:\n"
            "• A1: Present Simple, Present Continuous, базовый Past Simple (be, go, see), модальный can, базовые предлоги (in, at, on), простые вопросы.\n"
            "• A2: Past Continuous, Present Perfect Simple (just, already, yet), Future (will, going to), Conditionals 0 и 1-й (if/when), модальные (should, must, have to), сравнительные степени.\n"
            "• B1: Present Perfect Continuous, Past Perfect (had done), 2-й Conditional (would + V), Passive Voice (Present/Past Simple), придаточные определительные (relative clauses: which, who, that), косвенная речь (reported speech), модальные предположения (might, could).\n"
            "• B2: 3-й Conditional (had been... would have done), Mixed Conditionals, Passive всех времен и модальный пассив, конструкции Wish / If only, Causative (have/get smth done), союзы противопоставления (whereas, despite, nevertheless), инверсии.\n"
            "• C1/C2: Сложные причастные обороты (Having finished...), эмфатические конструкции Cleft sentences (What surprised me was...), сложные инверсии (No sooner had...), субъюнктив (It is crucial that he be...), сложные идиомы.\n\n"
            "2. ЛЕКСИКА:\n"
            "• A1: Базовый быт, семья, еда, простые действия, цифры, цвета, погода.\n"
            "• A2: Покупки, работа, транспорт, здоровье, хобби, базовые фразовые глаголы.\n"
            "• B1: Описание чувств, планов, мнений, путешествия, социальные темы, базовые абстрактные понятия.\n"
            "• B2: Профессиональная, деловая, академическая лексика, устойчивые фразовые глаголы и коллокации.\n"
            "• C1/C2: Академические/юридические термины, узкоспециализированная лексика, идиоматические выражения, метафоры."
        )

    elif code in ("no", "nb", "nn"):
        return (
            "КРИТЕРИИ CEFR ДЛЯ НОРВЕЖСКОГО ЯЗЫКА (определяй уровень как МАКСИМУМ из сложности грамматики и сложности лексики):\n\n"
            "1. ГРАММАТИКА:\n"
            "• A1: Presens, Preteritum (слабые и простые сильные глаголы), прямой порядок слов и базовое правило инверсии V2, притяжательные местоимения, базовые предлоги.\n"
            "• A2: Perfektum (har gjort), придаточные предложения с союзами fordi, at, hvis, da/når, модальные глаголы (skal, vil, må, bør, kan), степени сравнения прилагательных, возвратные местоимения (seg).\n"
            "• B1: Pluskvamperfektum (hadde gjort), Passiv с s-verb и bli-passiv (ble skrevet), инфинитивные обороты (for å...), союзы selv om, mens, ettersom, действительные и страдательные причастия (partisipper).\n"
            "• B2: Двойные союзы (jo... desto, ikke bare... men også), согласование причастий (samsvarsbøying), сложные условные конструкции (hadde jeg visst...), косвенная речь, инверсии в начале предложения.\n"
            "• C1/C2: Сложные причастные конструкции, пассивные стилистические обороты, инверсивные стилистические структуры, устойчивые идиоматические обороты, формальный/академический синтаксис.\n\n"
            "2. ЛЕКСИКА:\n"
            "• A1: Базовый быт, еда, семья, числа, простые глаголы действия.\n"
            "• A2: Покупки, работа, путешествия, здоровье, базовые хобби и повседневные темы.\n"
            "• B1: Описание чувств, планов, мнений, стандартные абстрактные понятия, обсуждение новостей.\n"
            "• B2: Профессиональная, деловая, общественно-политическая лексика, устойчивые выражения.\n"
            "• C1/C2: Академические и юридические термины, идиомы, метафоры, стилистически окрашенная лексика."
        )

    else:
        # Default German (de)
        return (
            "ОПЕРАЦИОННАЯ СИСТЕМА КЛАССИФИКАЦИИ УЧЕБНЫХ ФРАЗ:\n\n"
            "ПРАВИЛА ОЦЕНКИ:\n"
            "1. Не определяй уровень по общему впечатлению от фразы.\n"
            "2. Сначала найди конкретные грамматические конструкции и сложную лексику.\n"
            "3. Уровень отдельной конструкции не равен уровню всего предложения.\n"
            "4. grammar_level = уровень самой сложной грамматической конструкции в предложении.\n"
            "5. vocabulary_level = уровень самого сложного существенного слова или устойчивого выражения.\n"
            "6. overall_level = МАКСИМУМ из grammar_level и vocabulary_level.\n"
            "7. Длина предложения не повышает уровень: оценивай только конкретные конструкции и лексику.\n\n"
            "1. ГРАММАТИЧЕСКАЯ КЛАССИФИКАЦИЯ:\n"
            "• A1:\n"
            "  - Präsens в простых утвердительных и вопросительных предложениях.\n"
            "  - Базовый порядок слов в главном предложении, формы sein, haben, отрицание nicht, kein.\n"
            "  - Nominativ и базовый Akkusativ, личные и притяжательные местоимения.\n"
            "  - Основные модальные глаголы в Präsens: können, müssen, wollen, dürfen, sollen, möchten.\n"
            "  - Базовые предлоги времени и места.\n"
            "  - Простые отделяемые глаголы в Präsens: aufstehen, einkaufen, anrufen.\n"
            "  - Imperativ в простых бытовых ситуациях.\n"
            "• A2:\n"
            "  - Perfekt как грамматическая конструкция: haben/sein + Partizip II (gemacht, gekauft, gegangen, gehört, eingegeben и др.).\n"
            "  - Отделяемые глаголы в Präsens и Perfekt.\n"
            "  - Präteritum основных часто употребляемых глаголов (war, hatte, musste, wollte, konnte).\n"
            "  - Dativ и предлоги Dativ (mit, nach, aus, zu, bei, von, seit).\n"
            "  - Возвратные глаголы (sich freuen, sich erinnern).\n"
            "  - Простые придаточные предложения с союзами weil, dass, wenn, ob, als (глагол в конце).\n"
            "  - Сравнительная степень прилагательных (größer, besser, am größten).\n"
            "  - Вежливые формы Konjunktiv II (möchte, könnte, hätte gern, wäre gern).\n"
            "  - Базовые конструкции с zu + Infinitiv.\n"
            "• B1:\n"
            "  - Придаточные предложения: obwohl, während, nachdem, bevor, seitdem, sodass.\n"
            "  - Инфинитивные конструкции: um ... zu, ohne ... zu, statt ... zu.\n"
            "  - Relativsätze (придаточные определительные: der, die, das, den, dem, deren).\n"
            "  - Passiv Präsens: wird gemacht, wird repariert.\n"
            "  - Полноценный Konjunktiv II для гипотез и условий (hätte, wäre, würde + Infinitiv).\n"
            "  - Plusquamperfekt, Futur I.\n"
            "  - Управление глаголов с предлогами (warten auf, denken an, sich interessieren für) и Pronominaladverbien (darauf, damit, daran).\n"
            "  - Предлоги с Genitiv: wegen, trotz, während, aufgrund.\n"
            "• B2:\n"
            "  - Passiv в сложных временах (ist gemacht worden, war gemacht worden) и с модальными (muss gemacht werden).\n"
            "  - Konjunktiv I и косвенная речь.\n"
            "  - Partizip I и Partizip II в роли распространенных определений.\n"
            "  - Сложные двойные союзы: je ... desto, nicht nur ... sondern auch, sowohl ... als auch, weder ... noch, zwar ... aber.\n"
            "  - Nomen-Verb-Verbindungen (eine Entscheidung treffen, zur Verfügung stehen).\n"
            "• C1/C2:\n"
            "  - sein + zu + Infinitiv, sich lassen + Infinitiv, сложные Partizipialkonstruktionen.\n"
            "  - Инверсия как средство организации текста, официальный, научный и академический синтаксис.\n\n"
            "2. ЛЕКСИЧЕСКАЯ КЛАССИФИКАЦИЯ:\n"
            "• A1: Быт, еда, семья, числа, время, погода, базовые действия (wohnen, essen, trinken, kaufen).\n"
            "• A2: Работа, банк, транспорт, здоровье, бытовые сервисы, базовая цифровая лексика (Passwort, Datei, App, herunterladen, anmelden, eingeben).\n"
            "• B1: Чувства, мнения, планы, аргументация, абстрактные понятия, обсуждение причин и последствий.\n"
            "• B2: Профессиональная, деловая, экономическая лексика (verschlüsseln, Verantwortung, Erfahrung).\n"
            "• C1/C2: Академическая, юридическая, научная лексика (Datenschutzbestimmung, Paradigmenwechsel), редкие идиомы."
        )
